[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'mattesgroeger/vim-bookmarks'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'vim-gitbranch'
hook_add = '''
  let g:lightline = {
        \ 'colorscheme': 'default',
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ],
        \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
        \ },
        \ 'component_function': {
        \   'filename': 'FilePath',
        \   'gitbranch': 'gitbranch#name'
        \ },
        \ }

	function! FilePath()
	  return expand("%:P")
	endfunction
'''


[[plugins]]
repo = 'skywind3000/asyncrun.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=100
  set signcolumn=yes
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  " layout - down / up / left / right
  let g:fzf_layout = { 'up': '~70%' }

  " file selector
  nnoremap <silent> ;f :FZFFileList<CR>
  command! FZFFileList call fzf#run({
              \ 'source': 'find . -type d -name .git -prune -o ! -name .DS_Store ! -name "*~"',
              \ 'options': '--exact --reverse',
              \ 'sink': 'e'})

  " grep
  nnoremap <silent> ;g :Grep<CR>
  command! -bang -nargs=* Grep
    \ call fzf#vim#grep(
    \   'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))

  " under cursor grep
  nnoremap <silent> ;s :Find<CR>
  command! -bang -nargs=* Find
    \ call fzf#vim#grep(
    \   'rg --column --line-number --no-heading --color=always '.shellescape(expand('<cword>')), 1,
    \   <bang>0 ? fzf#vim#with_preview('up:60%')
    \           : fzf#vim#with_preview('right:50%:hidden', '?'),
    \   <bang>0)
'''


[[plugins]]
repo = 'ap/vim-buftabline'
hook_add = '''
  let g:buftabline_show = 2
  let g:buftabline_numbers = 2

  highlight BufTabLineCurrent ctermbg=black
  highlight BufTabLineActive ctermbg=white
  highlight BufTabLineHidden ctermbg=darkgrey
  highlight BufTabLineFill ctermbg=grey
'''
